name: Coverage
on:
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - .github/workflows/coverage.yml
jobs:
  publish:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Generage coverage report
        run: npm run coverage
      - name: Push to store repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.STORE_DEPLOY_KEY }}
        with:
          source-directory: 'coverage'
          target-directory: 'coverage'
          destination-github-username: 'nishantwrp'
          destination-repository-name: 'joplin-plugin-templates-store'
          create-target-branch-if-needed: true
          commit-message: 'chore: update coverage report (ORIGIN_COMMIT)'
          user-name: 'Albus'
          user-email: 'bot@nishantwrp.com'
          target-branch: main
